---
apiVersion: v2
name: vh-booking-queue-subscriber
home: https://github.com/hmcts/vh-booking-queue-subscriber
version: 0.0.9
description: Helm Chart for VH Bookings Queue Subscriber
maintainers:
  - name: VH Devops

dependencies:
  - name: function
    version: 2.2.0
    repository: https://hmctspublic.azurecr.io/helm/v1/repo/

  - name: java
    version: 3.7.9
    repository: https://hmctspublic.azurecr.io/helm/v1/repo/